### ISSUE TITLE
Thoughts on [nearing] feature-parity with TeX `acronym`?

### ISSUE THREAD

**Issue by jmuchovej** [Grisely/packages#7]
### Description

Mainly, I was looking for [TeX's] `acronym`'s `acl` – which is easy enough to with the following, but I think it'd be nice to have a fairly thorough replication of TeX's `acronym` as well.

```typst
#let acrl(acr: str) = {display-def(acr, plural: false)}
```

For reference, `acronym`'s docs: https://mirrors.mit.edu/CTAN/macros/latex/contrib/acronym/acronym.pdf

I'd be happy to find some time to integrate some [or perhaps many] of these – but wanted to check before spending the time. 🙂

**Comment by Grisely** [comment]
Indeed, some of the commands from `acronyms` could be useful. There are much more than I ever used.
Feel free to implement the ones you find useful. Try to reuse the piece of code already present as much as possible to keep the result consistent and easy to debug.

**Comment by bbenno** [comment]
Just for anyone ending up here....

With v0.4 it is:

```typst
#let acrs = display-short
#let acrl = display-def
```

**Comment by Grisely** [comment]
I will look into the parity next, but for now if you are looking for shortcuts you can build them easily by calling existing functions with arguments if required as @bbenno mentioned.

As of 0.4.1, these easy shortcuts works:

```
#let acresetall = reset-all-acronyms
#let ac = acr
#let acf(acro) = acrf(acro)
#let acfp(acro) = acrfpl(acro)
#let acs(acro) = display-short(acro,plural:false)
#let acsp(acro) = display-short(acro,plural:true)
```

**Comment by Grisely** [comment]
I added some relevant functions in the latest release 0.5.0 so I will consider this issue closed. Fell free to open another if specific functions are required.
