### ISSUE TITLE
Seperation of key and acronym

### ISSUE THREAD

**Issue by ChHecker** [Grisely/packages#8]
### Description

Thank you for this great package!
I'd like to propose one feature: Sometimes, the acronym itself is not a simple string, but needs features only allowed in content. In this case, it would be useful to define a separate key as a string used inside `#acr`, and a shorthand that allows `content`.

**Comment by Grisely** [comment]
I think I understand that you want the `#acr("ARC")` function to not display "ARC" as the short version but another pre-defined piece of content. Could you provide an example of the code and the result you would like to achieve?

Also, I recently noticed that acronym definitions are not limited to strings but can be any piece of content. I suggest you take a look at the [Advanced Definitions](https://github.com/Grisely/packages/tree/main/packages/preview/acrostiche/0.4.0#advanced-definitions) section of the [readme](https://github.com/Grisely/packages/blob/main/packages/preview/acrostiche/0.4.0/README.md) and see if that can solve your case.

**Comment by ChHecker** [comment]
The advanced definitions only allow the long version of the acronym to be `content`, right?

For my idea, maybe one could allow the acronym definitions to be a dictionary? Something like
```typst
#init-acronyms((
  "MCA": (
     short: smallcaps("mca"),
     long:  "My Custom Acronym",
     short-pl: [#smallcaps("mca")s],
     long-pl: "My Custom Acronyms",
  )
))
```
Arrays could be kept around for backwards compatibility by checking for the type.

**Comment by Grisely** [comment]
I like the idea of having a simple and backward compatible definition with array and an advanced definition with dictionaries. I'll try to implement.

**Comment by Grisely** [comment]
@ChHecker I implemented a minimal version of it in the last two commit. It should work for the simple cases with both singular and plural. Feel free to give it a try.
There is an argument to be made about what should be the short version if the "short" key is not in the definition: Should it default to the key passed as argument or should it panic and refuse to compile. Let me know if you have a preferred approach, I am on the fence. (same for the long versions and the missing keys).

**Comment by ChHecker** [comment]
Thanks for implementing my request! I think it should default to the key.
